config/routes.rb
Zephyr::Application.routes.draw do

  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :car_listings,        only: [:new, :create, :destroy]
  resources :driver_applications, only: [:new, :create, :destroy]
  resources :car_slots,           only: [:update]

  root 'home#index'
  match '/list',            to: 'car_listings#new',              via: 'get'
  match '/list_submitted',  to: 'car_listings#submitted',        via: 'get'
  match '/drive',           to: 'driver_applications#new',       via: 'get'
  match '/drive_submitted', to: 'driver_applications#submitted', via: 'get'
  match '/dashboard',       to: 'dashboard#show',                via: 'get'
  match '/schedule',        to: 'schedule#show',                 via: 'get'
  match '/profile',         to: 'profile#show',                  via: 'get'

  if Rails.env.development?
    mount MailPreview => 'mail_view'
  end

end

app/views/layouts/_footer.html.erb
<footer class="footer divider-inside-top">
  <div class="container" id="footer">
    <div class="row">
      <div class="col-md-6" id="footerLeft">
        © 2014 Babel Mail - Connect with the World
      </div>
      <div class="col-md-6" id="footerRight">
        Contact Us &nbsp;&nbsp; | &nbsp;&nbsp;<a href="mailto:hello@babel-mail.com" >hello@babel-mail.com</a>
      </div>
    </div>
  </div>
  <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-46434116-1', 'zephyrcar.com');
  ga('send', 'pageview');

</script>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header babel-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#babel-navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand babel-brand" href="/"><%= image_tag "babel-small.png", class: "babel-brand-img" %> Babel Mail</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="babel-navbar-collapse">
      <ul class="nav navbar-nav" id="babel-main-links">
        <li><a href="#how-it-works">How it works</a></li>
        <li><a href="#languages-and-pricing">Languages & Pricing</a></li>
        <li><a href="#try-it-free">Try it FREE</a></li>
      </ul>
      <ul class="nav navbar-nav pull-right">
      <%= javascript_include_tag "dropdown_menu" %>
          <% if user_signed_in? %>
            <%= render 'layouts/navbar_signed_in' %>
          <% else %>
            <%= render 'layouts/navbar_signed_out' %>
          <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<!--nav class="navbar navbar-default" role="navigation">
  <div class="container">
    <div class="row">
      <div class="col-sm-4 col-sm-offset-4 col-xs-12" id="logo">
        <center><%= link_to "ZEPHYR", root_path, id: "logo" %></center>
      </div>
      <div class="col-sm-4 col-xs-12" id="header-right">
        <center>
          <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
          </div>

          <%= javascript_include_tag "dropdown_menu" %>
          <% if user_signed_in? %>
            <%= render 'layouts/navbar_signed_in' %>
          <% else %>
            <%= render 'layouts/navbar_signed_out' %>
          <% end %>

          </div>
        </center>
      </div>
    </div>
  </div>
</nav-->
<div style="width:100%;">
<% flash.each do |key, value| %>
  <% if key == :notice %>
    <div class="alert alert-success ephemeral"><%= value %></div>
  <% else %>
    <div class="alert alert-danger ephemeral"><%= value %></div>
  <% end %>
<% end %>
</div>

app/views/layouts/_navbar_signed_in.html.erb
<li>
  <a href="#" data-toggle="dropdown" id="signed-in-dropdown"><span id="user_email"><%= current_user.email %></span>
    <span class="glyphicon glyphicon-cog"></span>
    <b class="caret"></b>
  </a>
  
  <ul class="dropdown-menu signed-in pull-right" id="nav-dropdown" role="menu">
    <b id="arrow-up"></b>
    <li>
      <%= link_to("Driving schedule", schedule_path, id: "dropdown-schedule", class: "btn btn-default btn-block") %>
    </li>
    <li>
      <%= link_to "Profile", profile_path, class: "btn btn-default btn-block" %>
    </li>
    <li>
      <%= button_to "Sign out", destroy_user_session_path, method: "delete", class: "btn btn-default btn-block" %>
    </li>

  </ul>
</li>

app/views/layouts/_navbar_signed_out.html.erb
<li>
  <%= link_to("Sign up", "#", id: "header-CTA") %>
</li>
<li>
  <a href="#" class="dropdown-toggle CTA" id="header-signin" data-toggle="dropdown">
    Login <span class="caret"></span>
  </a>
  <ul class="dropdown-menu signed-out pull-right" role="menu">
    <%= form_for(resource, :as => resource_name, :url => session_path(resource_name)) do |f| %>
      <li class="form-group">
        <%= f.email_field :email, class: "form-control", placeholder: "Email", :autofocus => true %>
      </li>
      <li class="form-group">
        <%= f.password_field :password, class: "form-control", placeholder: "Password" %>
      </li>
      <li class="divider"></li>
      <li class="form-group">
        <%= f.submit "Sign in", class: "btn btn-primary btn-block" %>
      </li>
      <li class="form-alt-link">
        <%= link_to "Forgot your password?", new_password_path(resource_name) %>
      </li>
    <% end %>
  </ul> 
</li>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
	  <title>Babel Mail</title>
	  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
	  <script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
	  <link href='http://fonts.googleapis.com/css?family=Allan:700' rel='stylesheet' type='text/css'>
	  <link href='http://fonts.googleapis.com/css?family=Alegreya+Sans' rel='stylesheet' type='text/css'>
	  <link href='http://fonts.googleapis.com/css?family=Varela' rel='stylesheet' type='text/css'>
	  <link href='http://fonts.googleapis.com/css?family=Oswald' rel='stylesheet' type='text/css'>
	  <link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>
	  <link href='http://fonts.googleapis.com/css?family=Reenie+Beanie&amp;subset=latin' rel='stylesheet' type='text/css'>
	  <link rel="shortcut icon" href="assets/babel-logo.ico" >

	  <script type="text/javascript">
	    (function(c,a){window.mixpanel=a;var b,d,h,e;b=c.createElement("script");
	    b.type="text/javascript";b.async=!0;b.src=("https:"===c.location.protocol?"https:":"http:")+
	    '//cdn.mxpnl.com/libs/mixpanel-2.2.min.js';d=c.getElementsByTagName("script")[0];
	    d.parentNode.insertBefore(b,d);a._i=[];a.init=function(b,c,f){function d(a,b){
	    var c=b.split(".");2==c.length&&(a=a[c[0]],b=c[1]);a[b]=function(){a.push([b].concat(
	    Array.prototype.slice.call(arguments,0)))}}var g=a;"undefined"!==typeof f?g=a[f]=[]:
	    f="mixpanel";g.people=g.people||[];h=['disable','track','track_pageview','track_links',
	    'track_forms','register','register_once','unregister','identify','alias','name_tag','set_config',
	    'people.set','people.set_once','people.increment','people.track_charge','people.append'];
	    for(e=0;e<h.length;e++)d(g,h[e]);a._i.push([b,c,f])};a.__SV=1.2;})(document,window.mixpanel||[]);
	    mixpanel.init("ec6a353b00dcc25b5b418fdbbf4d6a94");
	  </script>

    <%= stylesheet_link_tag "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %> 
    <%= render 'layouts/shim' %>

	</head>

	<body>
	  <%= render 'layouts/header' %>
	  <%= yield %>
	  <%= render 'layouts/footer' %>
	</body>
</html>